# Use postgres/example user/password credentials
version: '3.8'

services:
  db:
    image: postgres:${POSTGRES_VERSION}
    # restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - "TZ=America/Bogota"
    ports:
      - '5432:5432'
    volumes: 
      - taller_api:/var/lib/postgresql/data
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"

volumes:
  taller_api: